### ISSUE TITLE
Drive Details / Drive does not show the correct Y-Legend

### ISSUE THREAD

**Issue by metawatchkalle** [teslamate-org/teslamate#2785]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

In DriveDetails/Drive dashboard the Y-Axis-Legend stays on kW. In older versions the legend switches to the correct unit. e.g. km/h or percent or km.....

![Drive-Legend](https://user-images.githubusercontent.com/4587701/179966526-4cb3d85f-1c8d-40fe-90f0-1bef8d755648.jpg)

### Expected Behavior

Y-Axis should display the correct unit when switching to different curves.

### Relevant log output

```shell
not available
```

### Type of installation

Docker

### Version

1.27.0

**Comment by woyteck1** [comment]
In 1.26.0 the legend was on both left and right side and it was good. Now I get both legends on left side and it's a mess.
Also ZERO should be in the SAME place for all data. This is like violation fo good graph design. Hurts my eyes :(
![image](https://user-images.githubusercontent.com/25311523/180667505-cea231af-d6a1-4aa0-acf8-8649efb3faf2.png)

**Comment by adriankumpf** [comment]
With the recent TeslaMate update, the Graph plugin was upgraded to the new time series panel. So everything had to be built from scratch.

Do you want to send a PR with the panel customized to your liking? If you click on the arrow in the panel header you can edit the chart and, for example, change the axis settings.

**Comment by woyteck1** [comment]
OK. Now I understand. Apologies but I feel really strongly about my graphs ;) I will do this soon and submit a PR.

**Comment by woyteck1** [comment]
So, after some digging, I think I found what the problem is.
Old grafana had only 2 options for Y-axis, and in old version values were either "Locale format" (left side) or "short" (right side) and it worked well.
Now cue in the new Grafana v8.5.6 (or whatever), and this one has only one Y-axis, but allows overrides for all and any values.
It also gives an opportunity to use correct units instead of renaming the data just on the graph.
And you rightly went and used this opportunity, and rightly so, because it makes sense to have correct unit for every type of metrics that is being measured. 
However, that caused the Grafana to completely ignore the values in the data, because "different units cannot be showed on the same Y axis", hence is now really impossible to nicely set the values, even in groups.
When all of the Units are enabled to show on the Y-axis, you can clearly see how much of a mess this is (see screen grab below.
![image](https://user-images.githubusercontent.com/25311523/183528376-52329999-f737-4d79-8099-679c130db8c5.png)

There is a way to fix this, but it basically requires to go back to the old formula for this graph.
```
SELECT
	$__time(date),
	convert_km(speed::numeric, '$length_unit') AS "Speed [$length_unit/h]",
	power AS "Power [kW]",
	battery_heater::integer*100 AS "Preconditioning",
	convert_km([[preferred_range]]_battery_range_km, '$length_unit') AS "Range ($preferred_range) [$length_unit]",
	convert_km(est_battery_range_km, '$length_unit') AS "Range (est.) [$length_unit]",
	battery_level AS "SOC [%]",
	usable_battery_level AS "usable SOC [%]"
FROM
	positions
WHERE
 car_id = $car_id AND
 $__timeFilter(date)
ORDER BY
	date ASC
```
Fear not, it is still possible to use the goodness of override for some of the data (namely Battery heater), but generally values just need to stay without unit for this complicated graph to work well. Otherwise it's just a mess.

I will soon probably have a fix for this, if anyone is willing to go back to a similar version of the old graph, but I think it was the best version.

**Comment by woyteck1** [comment]
I managed to get down to this, more classic view on the new Grafana with just changing the Unit value to Locale format or short as it was in the old setup:
![image](https://user-images.githubusercontent.com/25311523/183529695-38234746-767d-4690-ad98-29e492dfa06e.png)

Let me know if this one is better looking (of course we will need to add back the Units in the Legend).

**Comment by woyteck1** [comment]
Or this one - this looks like the old one from v1.26.1
![image](https://user-images.githubusercontent.com/25311523/183531545-cf5a87d4-7c2b-4948-9b01-369489b1bc19.png)

**Comment by woyteck1** [comment]
So, I have opened this with Grafana after this, and guess what - they have added an option "Centered zero" in the 9.1
https://github.com/grafana/grafana/issues/53431
Thus I'd suggest to update grafana to 9.1 - https://github.com/grafana/grafana/pull/52555

**Comment by DrMichael** [comment]
"Centered zero" does not make sense.
