### ISSUE TITLE
should send mqtt message if charger connected but no power

### ISSUE THREAD

**Issue by brianmay** [teslamate-org/teslamate#3078]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

After a while charger cables stop working for me, and Tesla reports No Power. Would like to be able to monitor this condition so I can send alerts to get the problem fixed.

Which this happens, I believe the charge state has a `charging_state` field which is set to `"NoPower"`.

But unfortunately this value is not sent to MQTT - not that I can see anyway.

### Relevant log output

```shell
Nothing relevant. By default the charge_state value is not logged.
```

### Additional data

Not sure if a bug report is really relevant, but support request didn't seem to be relevant either.

I am thinking of attempting to create a pull request that will just publish the `charging_state` field to a new MQTT topic. But wanted to get feedback if people thought that was a good idea or not.

### Type of installation

Docker

### Version

1.27.2

**Comment by EasternPA** [comment]
I ended up throwing something together with Node-RED for a buddy of mine. His discount kicks in at 10 pm, and he drives 40 miles/day with his SR+. I assembled a flow that pulls the geofence, charge_port_door_open, charger_actual_current, and usable_battery_level into flow variables. When he first bought the car, he wouldn't insert the charging handle far enough into the port to make a connection.

So on nights before a work day, the flow checks at 10:05 PM to see:

- if he's home
- if the charge port door is open
- if the charging voltage is 0, and
- if the SoC is below 60% 

If all those conditions are met, send him a text message warning him to check the car since it's not charging (and may be too low to get through the next day). It also emails him (and me for troubleshooting). I eventually had to shut it off, though. TM was late detecting that the charge had started by half an hour or more, resulting in several false alarms. He would send me screenshots of the warning from NR and Tessie showing it was charging just fine.
