### ISSUE TITLE
Feature request: download Supercharging invoices

### ISSUE THREAD

**Issue by RichieB2B** [teslamate-org/teslamate#3266]
TeslaFi and TelsaLogger now support this: 
https://support.teslafi.com/communities/1/topics/8-changelog#comment-27971
https://github.com/superfloh247/TeslaLogger/blob/master/TeslaLogger/GetChargingHistoryV2Service.cs

**Comment by cwanja** [comment]
#1831 not sure this API is still available. But it's 'unofficial' at best.

**Comment by killtux** [comment]
hey @JakobLichterfeld, there is now an official way to download the invoices with api:
https://developer.tesla.com/docs/fleet-api#charging_invoice

this would be such a cool feature if teslamate can download all new invoices automatically and sent them to yourself over email. its so annoying that tesla doesnt do this automatically. is there a chance to have this feature integrated somehow?

you could also pull the charging price/data from it so you dont have to manually add every external charging cost in the grafana statistic.

**Comment by brianmay** [comment]
Sending outgoing emails is something that sounds easy, but needs to be done with care to ensure you aren't accidentally black listed for sending spam. Which isn't to put anybody off from implementing, just in needs to be done with care.

Probably need to have config for outgoing SMTP server: hostname, port, username, password, from address, to address, etc.

**Comment by parkr** [comment]
It would be a big feature request but we could also just archive them for download from the API. As part of a supercharger charge on the Charge Details page, a user could download them. Agreed email is a huge dependency to add.

It's actually something that a third party/extension could easily add too, since invoices are generated later anyway: Once a day download any invoices that haven't been processed yet, parse them, and write the cost to the charges teslamate database table. It'd be better to have a teslamate http API for updating charge details, but it's possible.

**Comment by DrMichael** [comment]
> this would be such a cool feature if teslamate can download all new invoices automatically and sent them to yourself over email. its so annoying that tesla doesnt do this automatically. is there a chance to have this feature integrated somehow?

That would better be done by something like node-red: pull invoice with fleet API (which we do not use) and send it via email.

**Comment by killtux** [comment]
if anyone has the skill to write an third party extension for teslamate (or even a node-red script), maybe this could be helpful:
https://gist.github.com/egavard/3f0d8decb600dcd79c7ddc57d8392d8c

it's so annoying to use the tesla mobile app to download every single pdf invoice. i think many users would really appreciate such feature.
