### ISSUE TITLE
Grafana BUG DOCKER

### ISSUE THREAD

**Issue by SiNaPsEr0x** [teslamate-org/teslamate#3420]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

grafana latest not run

### Expected Behavior

to fix I reinstall 1.27.3 in the docker-compose.yml

### Steps To Reproduce

```
CONTAINER ID   IMAGE                              COMMAND                  CREATED          STATUS                          PORTS                              NAMES
8216b12833d4   seblucas/alpine-mosquitto:latest   "/usr/sbin/mosquitto…"   25 seconds ago   Up 18 seconds                   0.0.0.0:1883->1883/tcp, 9001/tcp   teslamate-mosquitto-1
52339cde836e   teslamate/teslamate:latest         "tini -- /bin/sh /en…"   25 seconds ago   Up 19 seconds                   0.0.0.0:4000->4000/tcp             teslamate-teslamate-1
23f9cedf979a   teslamate/grafana:latest           "/run.sh"                25 seconds ago   Restarting (139) 1 second ago                                      teslamate-grafana-1
8f0fd4567a31   arm32v7/postgres:15-alpine3.17     "docker-entrypoint.s…"   25 seconds ago   Up 18 seconds                   0.0.0.0:5432->5432/tcp             teslamate-database-1
[/share/Container/container-station-data/application/teslamate] # docker compose logs grafana
[/share/Container/container-station-data/application/teslamate] # docker compose logs grafana
[/share/Container/container-station-data/application/teslamate] # 

```

### Type of installation

Docker

### Version

1.27.4

**Comment by SiNaPsEr0x** [comment]
partial log is:

```
teslamate-mosquitto-1  | 1699871738: Opening websockets listen socket on port 9001.
teslamate-mosquitto-1  | 1699871738: mosquitto version 2.0.11 running
teslamate-database-1   | 2023-11-13 10:35:39.211 UTC [1] LOG:  starting PostgreSQL 15.4 on arm-unknown-linux-musleabihf, compiled by gcc (Alpine 12.2.1_git20220924-r4) 12.2.1 20220924, 32-bit
teslamate-database-1   | 2023-11-13 10:35:39.212 UTC [1] LOG:  listening on IPv4 address "0.0.0.0", port 5432
teslamate-database-1   | 2023-11-13 10:35:39.212 UTC [1] LOG:  listening on IPv6 address "::", port 5432
teslamate-database-1   | 2023-11-13 10:35:39.332 UTC [1] LOG:  listening on Unix socket "/var/run/postgresql/.s.PGSQL.5432"
teslamate-database-1   | 2023-11-13 10:35:39.656 UTC [23] LOG:  database system was shut down at 2023-11-13 10:34:28 UTC
teslamate-database-1   | 2023-11-13 10:35:39.819 UTC [1] LOG:  database system is ready to accept connections
**teslamate-grafana-1 exited with code 0**
teslamate-teslamate-1  | 2023-11-13 10:35:44.307 [info] Migrations already up
teslamate-grafana-1 exited with code 139
teslamate-teslamate-1  | 2023-11-13 10:35:52.228 [info] System Info: Erlang/OTP 26 (emu)
teslamate-teslamate-1  | 2023-11-13 10:35:52.228 [info] Version: 1.27.4
```

**Comment by DrMichael** [comment]
I would do a database backup, clean out docker and make a fresh installation and restore the backup.

**Comment by SiNaPsEr0x** [comment]
The problem remains I had already tried... the problem is not the reading but the latest version of grafana not compatible with armv7 despite the binaries are present on the docker .. while version 1.27.3 works perfectly

**Comment by BluSpanner** [comment]
Try grafana v10.1.2
Note: The last docker image for arm/v7 is currently grafana grafana/grafana:10.1.2

**Comment by SiNaPsEr0x** [comment]
ok but in the teslamate repository on docker there is a armv7 release --> https://hub.docker.com/layers/teslamate/grafana/latest/images/sha256-2219c19b4e64284297c28e455d09158bc566fb39b787bd8454a7841771aa2101?context=explore

but not run correctly.. Likely an oversight during the release of the update?

**Comment by SiNaPsEr0x** [comment]
on version 1.27.3 of repository teslamate there is this version:

teslamate-grafana-1  | logger=settings t=2023-11-13T11:37:53.45+0000 lvl=info msg="Starting Grafana" version=8.5.26 commit=e4fd9da88e branch=HEAD compiled=2023-05-22T10:26:26Z

**Comment by SiNaPsEr0x** [comment]
@adriankumpf for armv7 there is hubimage/grafana:master run correctly ... for your arm32bit can you fix this?

**Comment by swiffer** [comment]
the bundled docker release of 1.27.4 is 9.5.10 - adrian downgraded from 9.5.13 as it's not available for arm/v7 currently.

https://github.com/teslamate-org/teslamate/commit/446ceed04f970fdc9de236e9d0e77a43b2c9e6fd

**Comment by SiNaPsEr0x** [comment]
> the bundled docker release of 1.27.4 is 9.5.10 - adrian downgraded from 9.5.13 as it's not available for arm/v7 currently.
> 
> 
> 
> https://github.com/teslamate-org/teslamate/commit/446ceed04f970fdc9de236e9d0e77a43b2c9e6fd

Thanks but this is a very problem for more nas

**Comment by SiNaPsEr0x** [comment]
Is there a way to create a docker repository with teslamate/grafana info on your own?

**Comment by swiffer** [comment]
yes, the current version should work. can you try dropping your local images and fetch them again from docker hub?
I found this issue which looks similar https://github.com/teslamate-org/teslamate/issues/547
i can't test as i do not have arm/v7 hardware in place

**Comment by JakobLichterfeld** [comment]
Can't confirm this issue, no issue on ArmV7 with TeslaMate 1.27.4. you need to do a`docker compose pull` to fetch appropriate grafana docker image as well.

**Comment by elpanda88** [comment]
> resolved to clean all db and reimport problem is upload interrupt... thanksss close ticket

Hi @SiNaPsEr0x (or ciao, i'm italian too) . I'm having the same problem you had. It started happening once i pulled version 1.28.3. Grafana won't start. when adrian released version 1.28+ i solved everything using teslamatefork repository but now it's not available anymore. 
My hardware is close to yours so i bet that it's too related to armv7 architecture specific compiled version.
Would you be please so kind to show me your latest yml file in order to allow me to make grafana work again?
I tried to make fresh install (from version 1.28.0) and restore the dump backup files of my previous ps installation but without success (grafana still stuck). 
Should i avoid any upgrade at the moment and stay just with version 1.27.3 (both on grafana and teslamate daemon subcontainers)? Would that work? I was worried to lose connection through my car since tesla recently started using new authentication method... 

Let me know please. 
Its not urgent because i see the daemon correctly writing data on my postgres db... but Grafana is totally stuck!
oh, I forgot to mention: now i'm using postgres version 14. i tried 15 as well but nothing changed! 
For reference, i attach here my yml content so you can have a look!
Many thanks!!!

<img width="1023" alt="image" src="https://github.com/teslamate-org/teslamate/assets/85503068/ab445592-69db-432b-ac2b-7558647c67f0">
<img width="1576" alt="image" src="https://github.com/teslamate-org/teslamate/assets/85503068/909003f2-2dcd-45a9-a57e-d9d95425fd67">


TESLAMATE YML FILE FOR ARMv7 NOT WORKING (grafana issue)  yyyy/mm/dd 2024/02/09
####################################################################
version: "3"

services:
  teslamate:
    image: teslamate/teslamate:latest
    restart: always
    environment:
      - ENCRYPTION_KEY=MYPERSONALKEY
      - DATABASE_USER=teslamate
      - DATABASE_PASS=secret
      - DATABASE_NAME=teslamate
      - DATABASE_HOST=database
      - MQTT_HOST=mosquitto
    ports:
      - 4000:4000
    volumes:
      - ./import:/opt/app/import
    cap_drop:
      - all

  database:
    image: postgres:14.0-alpine
    restart: always
    environment:
      - POSTGRES_USER=teslamate
      - POSTGRES_PASSWORD=secret
      - POSTGRES_DB=teslamate
###    ports:
###      - 5432:5432 #####I opened this port to be able to query the db from a client
    volumes:
      - teslamate-db:/var/lib/postgresql/data

  grafana:
    image: teslamate/grafana:latest
    restart: always
    environment:
      - DATABASE_USER=teslamate
      - DATABASE_PASS=secret
      - DATABASE_NAME=teslamate
      - DATABASE_HOST=database
    ports:
      - 3000:3000
    volumes:
      - teslamate-grafana-data:/var/lib/grafana

  mosquitto:
    image: eclipse-mosquitto:2.0.14
    restart: always
    command: mosquitto -c /mosquitto-no-auth.conf
    ports:
      - 1883:1883
    volumes:
      - mosquitto-conf:/mosquitto/config
      - mosquitto-data:/mosquitto/data

volumes:
  teslamate-db:
  teslamate-grafana-data:
  mosquitto-conf:
  mosquitto-data:

**Comment by SiNaPsEr0x** [comment]
Unfortunately I had to migrate to oracle for the new functions otherwise not working

**Comment by elpanda88** [comment]
...pardon? is it free? can you give me more information on that? i'm not familiar with oracle environment...

**Comment by SiNaPsEr0x** [comment]
Certo ... basta che ti registri e avrai una Shell vps con amd64 https://www.oracle.com/cloud/free/

**Comment by elpanda88** [comment]
Grazie mille, sei molto gentile. Ho dovuto registrare la carta di credito ma mi par di capire che sia gratuito.. ora ci perdo un'oretta.. vediamo se riesco a installare teslamate in questo ambiente e anche importare il backup di postgres..

**Comment by SiNaPsEr0x** [comment]
Fatto io... ti confermo puoi fare tutto a fattura zero... il limite sono i 30gb ma io con 85.000km con backup crontab sono a 1.5gb quindi penso che avrò spazio per molto tempo

**Comment by elpanda88** [comment]
Un'ultima cosa, che distribuzione hai usato? io ho familiarità con ubuntu... cosa mi consigli?

**Comment by SiNaPsEr0x** [comment]
Va bene ma io ho messo devianza
