### ISSUE TITLE
org.opencontainers.image.version not updated

### ISSUE THREAD

**Issue by Tazmanian79** [teslamate-org/teslamate#3425]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

On version 1.27.4 the version is not changed.  It still has 1.27.3

My container has version 1.27.4 but this label
org.opencontainers.image.version | v1.27.3

### Expected Behavior

Should be changed to 1.27.4

### Relevant log output

```shell
/
```

### Type of installation

Docker

### Version

v1.27.4

**Comment by DrMichael** [comment]
Where needs this to be changed?

**Comment by JakobLichterfeld** [comment]
I assume the issue is within the [github metadata action](https://github.com/docker/metadata-action), as we are not setting the metadata directly, but with the github action in our CD pipeline [here](https://github.com/teslamate-org/teslamate/blob/fba87d7e88be214b710def34ad77a4c1de4455c0/.github/workflows/buildx.yml#L40), and reference [here](https://github.com/teslamate-org/teslamate/blob/fba87d7e88be214b710def34ad77a4c1de4455c0/.github/workflows/buildx.yml#L114).

**Comment by brianmay** [comment]
If you look here: https://github.com/teslamate-org/teslamate/actions/runs/6842721996/job/18604511204

And expand the relevant sections it says:

```
  org.opencontainers.image.created=2023-11-12T19:37:52.289Z
  org.opencontainers.image.description=A self-hosted data logger for your Tesla  🚘
  org.opencontainers.image.licenses=MIT
  org.opencontainers.image.revision=1e7c9a460a9[38](https://github.com/teslamate-org/teslamate/actions/runs/6842721996/job/18604511204#step:3:45)175a0b3d2545b74f681672e3e6b
  org.opencontainers.image.source=https://github.com/teslamate-org/teslamate
  org.opencontainers.image.title=teslamate
  org.opencontainers.image.url=https://github.com/teslamate-org/teslamate
  org.opencontainers.image.version=v1.27.4
```

Which looks OK to me...

Wondering if this is a client side issue, client caching the old data or something.

**Comment by Tazmanian79** [comment]
seems to be ok now.
