### ISSUE TITLE
CI: Grafana Docker push fails

### ISSUE THREAD

**Issue by JakobLichterfeld** [teslamate-org/teslamate#3487]
The push of new grafana image fails due to auth, @jlestel 

https://github.com/teslamate-org/teslamate/actions/runs/6988327850/job/19015781415

v1.28.0

**Comment by rpearson-catdevnull** [comment]
Was just about to open an issue of not being able to see the LFP dashboards from PR #3311. This is probably related right?

**Comment by rpearson-catdevnull** [comment]
You’re missing the docker login command, which you have in your main teslamate build [here](https://github.com/teslamate-org/teslamate/blob/83b73a734bc32797d116e7bb595671ab0f945258/.github/actions/build/action.yaml#L42) in the build script for your grafana action.

You’ll need to log in for each action due to the scope of the login not persisting between the two actions I believe. They’re separate jobs so will run on two separate action runners

**Comment by JakobLichterfeld** [comment]
Yeah, assume the same. As soon as the job failed, I switch to pre-release, so not everybody is complaining :-) GHCR images are good.

**Comment by jlestel** [comment]
@JakobLichterfeld sorry for the oversight I pushed a fix that should allow you to push correctly.

**Comment by JakobLichterfeld** [comment]
> @JakobLichterfeld sorry for the oversight I pushed a fix that should allow you to push correctly.

No problem. We had already found it in a review, but we were both confused by the accidental deletion of the fork branch :-)

**Comment by JakobLichterfeld** [comment]
Will double-check tomorrow or on Monday before final releasing :-)

**Comment by JakobLichterfeld** [comment]
closed with #3491
