### ISSUE TITLE
Different values for Logged Distance

### ISSUE THREAD

**Issue by RamonMir20** [teslamate-org/teslamate#3727]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

The "Logged Distance" value is different in the "Efficiency" panels compared to "Battery Health", what is the correct value? thank you.

### Expected Behavior

The value should be unique across all panels.

### Relevant log output

```shell
*
```

### Type of installation

Docker

### Version

v1.28.3

**Comment by cwanja** [comment]
One comes from `positions` (Efficiency) and the other comes from `drives` (Battery Health). 

Personally think drives is more accurate. Thoughts @JakobLichterfeld ? @jheredianet any reason you used `positions`?

**Comment by jheredianet** [comment]
> One comes from `positions` (Battery Health) and the other comes from `drives` (Efficiency).
> 
> Personally think drives is more accurate. Thoughts @JakobLichterfeld ? @jheredianet any reason you used `positions`? It also takes longer to pull from `positions`.

Yes, it is as you described. Except that it takes longer to pull, because it's just a query pulling from: **(max(odometer) - min(odometer)**. It takes milliseconds no matter the thousands record you have. 

The reason why I've decided to do it so, it's because I think it's better to know the distance the car has taken since Teslamate began to be used, than how many kilometers or miles have been saved in the database. The difference between one value and another is what could not be saved, either due to disconnection from the car, areas without coverage or because your Teslamate has been out of service.

This question makes me think that, to avoid confusion, it would be good for both values to be in this Dashboard, so that the user has at hand the information about what could not be collected in the database.
I will make the necessary changes so that it can be seen in a future version.

**Comment by jheredianet** [comment]
This is the PR https://github.com/teslamate-org/teslamate/pull/3741

**Comment by cwanja** [comment]
Will be reflected in a future release @RamonMir20. Details in the pull request.
