### ISSUE TITLE
Wrong battery capacity in Battery Health

### ISSUE THREAD

**Issue by GaPhi** [teslamate-org/teslamate#4059]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

The battery capacity panel for my "Model S P100D Early-2019" reports 75kWh rather than 100kWh for the "new value".
The "battery capacity by mileage" reports around 90kWh remaining capacity.

### Expected Behavior

Capactity of 100kWh for P100D, 90kWh for 90D, 75kWh for 75D, ...

### Steps To Reproduce

Click on Battery Health in grafana

### Relevant log output

```shell
N/A
```

### Screenshots

![Capture](https://github.com/teslamate-org/teslamate/assets/15260469/45a25aa0-0b11-44f2-a5a3-d733151d6787)

### Type of installation

Docker

### Version

v1.30.0

**Comment by JakobLichterfeld** [comment]
Thanks for reporting! @jheredianet can you please take a look into the Model S battery capacity? Ty.

**Comment by USAFPride** [comment]
2015 Model S P85D reports 73.1
![image](https://github.com/teslamate-org/teslamate/assets/7792972/420bff91-896d-4159-aeb3-668158ef5f84)

**Comment by jheredianet** [comment]
Hi, first of all, the estimations on this dashboard on chargers, efficiency and in the range, you have in the database. So, the car model has nothing to do with it here.
The car itself or Tesla API nowhere reports the actual battery capacity. It is possible to connect an ODB to get an approximation of the nominal battery, but it is still not accurate. In addition, it would have to be done on the first day the car leaves the dealership.

@GaPhi in your case, in your case according to "ev-database" the usable battery of this car is 95kWh (not 100kWh)
![image](https://github.com/teslamate-org/teslamate/assets/45735191/ed1e71dc-96f7-43e8-b004-ebc2120379dd)

And the ranges (are quite similar to this dashboard). In this case the range is a reading (returned by the Tesla API), I mean, it's not an estimate as in the case of the battery capacity.
![image](https://github.com/teslamate-org/teslamate/assets/45735191/8ff0eb8a-af15-4ffe-ba11-04b94d2e288d)

If you see the hint of this dashboard:
![image](https://github.com/teslamate-org/teslamate/assets/45735191/6b122371-8e01-4f9c-b43d-4c2481163f4b)

That's why, the more data you have logged in Teslamate from your brand-new car the better. In your case, as the graph shows (battery capacity by mileage), that you have begun using Teslamate after your first 13,000kms.  There it does show that at that mileage you started with more than 95kWh more or less, and now it's around 87kWh. So, your estimated degradation (since you begun using Teslamate) is around 9% as reported in this dashboard. 

What I have to check is why usable (new and now) are showing wrong values. 

By the way, have you imported data from other loggers? Because I've seen that people who has, usually experiment this issue because the units (miles or kilometers) are not well converted in some cases (depending on how they were exported form the coming system). In the other hand, can you show as a screenshot of your Teslamate settings?
![image](https://github.com/teslamate-org/teslamate/assets/45735191/38b72bec-7ff1-4618-a9ad-f8549a2a69be)

**Comment by GaPhi** [comment]
Hi,

I use \d+ regex on trim_badging to get the commercial battery capacity. But
I only have my own car an not the whole list of possible values...

I do not find the P100DL model S car on ev-database. I confirm my car has a
100kWh battery (Early 2019 model, Ludicrous and FSD).

I bought the car when it was circa 10000km. No data was imported from
previous owner.

What surprises me is that the values seemed correct from the first
implementation ; it seems to be a regression to me.

I attach my teslamate settings screenshot.

**Comment by GaPhi** [comment]
I have a French gui
- with 'estimée' I get Usable (new) 75.9 kWh
- with 'théorique' I get Usable (new) 95.0 kWh

I do not actually understand why battery capacity is impacted by this setting, it is only the autonomy in distance that is, isn't it?

**Comment by jheredianet** [comment]
Yes, the ideal range represents the expected distance a vehicle can travel on a full battery charge. It assumes optimal conditions, such as driving at a steady 55 mph or 90km/h on level ground with moderate temperatures, therefore, it is less precise as it depends on your own driving habits and the topography of the terrain where you usually travel.
On the other hand, the rated range is slightly more conservative and reflects the distance the Environmental Protection Agency (EPA) estimates the car can go based on their tests. 

So, for getting the estimated capacity we must only consider rated range as the range panel does (For this case, I see that the user's preference should not be considered).

I will be fixed in the next release. 

Cheers!

**Comment by GaPhi** [comment]
After some thoughts, I imagine an explanation for the 5kWh difference between the computed capacity and the commercial data sheet of the car. 

I observed that the car continues to be able to drive after it reaches 1 or 0% of remaining energy. 

5kWh is probably explained as the reserve of energy when the car reaches 0% remaining bettery. It also exists with fossil energy cars...


Where it is important is thet this artifically degrades battery health result if you do not consider it in the computation...

Can we investigate this too?

Thanks!
