### ISSUE TITLE
Statistics Dashboard - Time Driven is Truncated

### ISSUE THREAD

**Issue by khorton** [teslamate-org/teslamate#4268]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

The hours in Time Driven in the Statistics dashboard is truncated to no more than 99h.  For example, in July 2024, it shows 41h51m and a distance driven of 7668 miles.  This would require an average speed of over 180 miles per hour.  The correct value seems to be 141h51m.

I can get plausible values if I edit the column units to be "duration (hh:mm:ss)"

This is likely related to [issue 2068](https://github.com/teslamate-org/teslamate/issues/2086)

### Expected Behavior

Show correct value for Time Driven

### Relevant log output

```shell
Not relevant
```

### Type of installation

Docker

### Version

v1.30.1

**Comment by JakobLichterfeld** [comment]
Thanks for reporting!

**Comment by swiffer** [comment]
this has been fixed in Grafana 11.3.0 (not yet released) - let's see if Grafana 11.3.0 includes a fix to the geomap zoom issue and let us update, if Grafana 11.3.0 is not including a fix for the zoom layer we might address this issue by switchung to a different unit as proposed in the issue description

https://github.com/grafana/grafana/pull/92656
