### ISSUE TITLE
New version? 

### ISSUE THREAD

**Issue by vbarrier** [teslamate-org/teslamate#4280]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

Hi, 

Last version is a bit old..

- It is not compatible with third party providers. There was a bug fixed after: #4095 
- docker compose use postgre=> v17 doesn't work need to downgrade

Any release date soon?

### Relevant log output

```shell
N/A
```

### Type of installation

Docker

### Version

v1.30.1

**Comment by cwanja** [comment]
This is not an issue.

**Comment by vbarrier** [comment]
This is totally an issue, has you can't follow guides & documentation

**Comment by cwanja** [comment]
> This is totally an issue, as you can't follow guides & documentation

Please point to an official guide or documentation that does not work with the current version. 

Additionally, check the PRs. Work is underway for newer versions. We do not have a release pattern and release when a version is ready.

**Comment by vbarrier** [comment]
Ax explained, I followed the guide: https://docs.teslamate.org/docs/guides/api/ which doesn't work with 1.30.1 => released on 10/07 because the authentification doesn't worked until #4095 fixed on 27/07.

Also instructions on the docker install page: https://docs.teslamate.org/docs/installation/docker use the postgres v17 that's doesn't work with 1.30.1

**Comment by cwanja** [comment]
The issue is then **documentation** is misleading before a release. In a shocking twist, documentation leads versus software being released. You can either create an issue for the documentation to be fixed or rest assured (by looking at the PRs) that a release is in the works.

**Comment by parkr** [comment]
I agree that regular releases would be helpful for the Teslamate community and started a discussion: https://github.com/teslamate-org/teslamate/discussions/4282

**Comment by parkr** [comment]
The setup docs being broken with the current release is a pretty big miss IMO since newcomers won’t have a functioning example from which to get started. From their perspective, it’s broken software. https://github.com/teslamate-org/teslamate/pull/4231#issuecomment-2395373675 was 2 weeks ago and mentions that the docs will be broken so maybe a follow-up issue from @swiffer could have helped, or publishing the docs only on a release.

**Comment by swiffer** [comment]
agree that having docs updated before release actually supporting postgres 17 is a miss. i think @JakobLichterfeld  is currently working hard on pushing out a new release. would agree that pushing docs only on release would have helped in this case.

the docs published to early issue had been flagged here as well: https://github.com/teslamate-org/teslamate/issues/4242

**Comment by JakobLichterfeld** [comment]
Unfortunately, the website deployment is not in our hands. Only Adrian has access to the Netifly deployment, which automatically deploys the website with the latest master. We can switch to a different branching strategy to avoid this, but in most cases it is fine to have the latest doc on the website. 
The postgres17 is unfortunate. We were aiming for a release the next day, but the refactoring with build and CI was more time consuming than expected, plus we all have other priorities.

That said, we can and will improve. My goal is to have more small releases than big ones. That's why I've automated as many steps as possible, and our CI ensures high quality at all times.

**Comment by JakobLichterfeld** [comment]
> The setup docs being broken with the current release is a pretty big miss IMO since newcomers won’t have a functioning example from which to get started. From their perspective, it’s broken software.

It's not, only a restore with data without the new migration fails, so we decided not to backroll the docs, as neither new users nor existing users are disturbed in normal operation.

**Comment by JakobLichterfeld** [comment]
> Oh misunderstanding - restore in v17 for existing users works, setup for new users with v17 is broken.

Thanks for clarification. Then I totally get the point, but no new users opened a ticket for this. Anyway, we are close to a release.

**Comment by vbarrier** [comment]
Hi there, please don't forget that also all the process to use third party provider with Fleet API doesn't work because of #4095. I needed to use :edge version in order to make it work.
